import 'package:flutter/material.dart';

/// Resolve NOME de ícone Material → [IconData] (decisão D4 do módulo de
/// Menus, Valdo 2026-08-04: tb_module.image_icon guarda a STRING do nome —
/// ex.: 'shopping_cart' — e o app renderiza pelo catálogo abaixo).
///
/// Catálogo CONST e curado (não usar IconData(codePoint) dinâmico — quebra o
/// tree-shake de ícones do build web). Nome desconhecido/nulo → null; quem
/// chama decide o fallback (Icons.folder no preview do form, Icons.apps_outlined
/// no menu do Home).
IconData? materialIconByName(String? name) {
  if (name == null) return null;
  return _materialIconsByName[name.trim().toLowerCase()];
}

const Map<String, IconData> _materialIconsByName = {
  // Navegação / organização
  'home': Icons.home,
  'apps': Icons.apps,
  'widgets': Icons.widgets,
  'dashboard': Icons.dashboard,
  'menu': Icons.menu,
  'folder': Icons.folder,
  'folder_open': Icons.folder_open,
  'topic': Icons.topic,
  'archive': Icons.archive,
  'inbox': Icons.inbox,
  'category': Icons.category,
  'label': Icons.label,
  'bookmark': Icons.bookmark,
  'star': Icons.star,
  'favorite': Icons.favorite,
  'extension': Icons.extension,
  'tune': Icons.tune,
  'settings': Icons.settings,
  'search': Icons.search,
  'visibility': Icons.visibility,
  'list': Icons.list,
  'list_alt': Icons.list_alt,
  'checklist': Icons.checklist,
  'fact_check': Icons.fact_check,
  'rule': Icons.rule,
  'task': Icons.task,
  'task_alt': Icons.task_alt,
  'assignment': Icons.assignment,
  'assignment_turned_in': Icons.assignment_turned_in,
  'description': Icons.description,
  'article': Icons.article,
  'notes': Icons.notes,
  'book': Icons.book,
  'menu_book': Icons.menu_book,
  'library_books': Icons.library_books,
  // Comercial / vendas
  'shopping_cart': Icons.shopping_cart,
  'add_shopping_cart': Icons.add_shopping_cart,
  'shopping_bag': Icons.shopping_bag,
  'shopping_basket': Icons.shopping_basket,
  'store': Icons.store,
  'storefront': Icons.storefront,
  'add_business': Icons.add_business,
  'point_of_sale': Icons.point_of_sale,
  'sell': Icons.sell,
  'local_offer': Icons.local_offer,
  'local_mall': Icons.local_mall,
  'local_grocery_store': Icons.local_grocery_store,
  'loyalty': Icons.loyalty,
  'redeem': Icons.redeem,
  'card_giftcard': Icons.card_giftcard,
  'campaign': Icons.campaign,
  'inventory': Icons.inventory,
  'inventory_2': Icons.inventory_2,
  'warehouse': Icons.warehouse,
  'qr_code': Icons.qr_code,
  'qr_code_scanner': Icons.qr_code_scanner,
  // Financeiro
  'attach_money': Icons.attach_money,
  'payments': Icons.payments,
  'paid': Icons.paid,
  'price_check': Icons.price_check,
  'credit_card': Icons.credit_card,
  'account_balance': Icons.account_balance,
  'account_balance_wallet': Icons.account_balance_wallet,
  'savings': Icons.savings,
  'currency_exchange': Icons.currency_exchange,
  'request_quote': Icons.request_quote,
  'receipt': Icons.receipt,
  'receipt_long': Icons.receipt_long,
  'calculate': Icons.calculate,
  'percent': Icons.percent,
  'local_atm': Icons.local_atm,
  // Relatórios / análise
  'bar_chart': Icons.bar_chart,
  'pie_chart': Icons.pie_chart,
  'show_chart': Icons.show_chart,
  'trending_up': Icons.trending_up,
  'trending_down': Icons.trending_down,
  'insights': Icons.insights,
  'analytics': Icons.analytics,
  'assessment': Icons.assessment,
  'leaderboard': Icons.leaderboard,
  'table_chart': Icons.table_chart,
  // Pessoas / acesso
  'person': Icons.person,
  'person_add': Icons.person_add,
  'people': Icons.people,
  'group': Icons.group,
  'groups': Icons.groups,
  'badge': Icons.badge,
  'account_circle': Icons.account_circle,
  'manage_accounts': Icons.manage_accounts,
  'admin_panel_settings': Icons.admin_panel_settings,
  'support_agent': Icons.support_agent,
  'contacts': Icons.contacts,
  'security': Icons.security,
  'shield': Icons.shield,
  'lock': Icons.lock,
  'lock_open': Icons.lock_open,
  'key': Icons.key,
  'password': Icons.password,
  'verified': Icons.verified,
  'verified_user': Icons.verified_user,
  'policy': Icons.policy,
  'gavel': Icons.gavel,
  'balance': Icons.balance,
  // Empresa / operação
  'work': Icons.work,
  'business': Icons.business,
  'business_center': Icons.business_center,
  'corporate_fare': Icons.corporate_fare,
  'apartment': Icons.apartment,
  'domain': Icons.domain,
  'home_work': Icons.home_work,
  'location_city': Icons.location_city,
  'factory': Icons.factory,
  'engineering': Icons.engineering,
  'construction': Icons.construction,
  'handyman': Icons.handyman,
  'build': Icons.build,
  'local_shipping': Icons.local_shipping,
  'agriculture': Icons.agriculture,
  // Lugares / geografia
  'map': Icons.map,
  'place': Icons.place,
  'location_on': Icons.location_on,
  'public': Icons.public,
  'language': Icons.language,
  'flag': Icons.flag,
  // Tempo / agenda
  'event': Icons.event,
  'calendar_today': Icons.calendar_today,
  'calendar_month': Icons.calendar_month,
  'schedule': Icons.schedule,
  'alarm': Icons.alarm,
  'timer': Icons.timer,
  'history': Icons.history,
  'update': Icons.update,
  'sync': Icons.sync,
  'autorenew': Icons.autorenew,
  // Tecnologia / comunicação
  'cloud': Icons.cloud,
  'cloud_upload': Icons.cloud_upload,
  'cloud_download': Icons.cloud_download,
  'backup': Icons.backup,
  'storage': Icons.storage,
  'dns': Icons.dns,
  'computer': Icons.computer,
  'laptop': Icons.laptop,
  'smartphone': Icons.smartphone,
  'devices': Icons.devices,
  'print': Icons.print,
  'camera_alt': Icons.camera_alt,
  'image': Icons.image,
  'phone': Icons.phone,
  'call': Icons.call,
  'contact_phone': Icons.contact_phone,
  'mail': Icons.mail,
  'email': Icons.email,
  'send': Icons.send,
  'chat': Icons.chat,
  'forum': Icons.forum,
  'sms': Icons.sms,
  'notifications': Icons.notifications,
  'info': Icons.info,
  'help': Icons.help,
  // Setores / diversos
  'medical_services': Icons.medical_services,
  'local_hospital': Icons.local_hospital,
  'local_pharmacy': Icons.local_pharmacy,
  'health_and_safety': Icons.health_and_safety,
  'medication': Icons.medication,
  'science': Icons.science,
  'biotech': Icons.biotech,
  'school': Icons.school,
  'restaurant': Icons.restaurant,
  'fastfood': Icons.fastfood,
  'local_cafe': Icons.local_cafe,
  'liquor': Icons.liquor,
  'directions_car': Icons.directions_car,
  'directions_bus': Icons.directions_bus,
  'two_wheeler': Icons.two_wheeler,
  'pedal_bike': Icons.pedal_bike,
  'flight': Icons.flight,
  'train': Icons.train,
  'sailing': Icons.sailing,
  'pets': Icons.pets,
  'forest': Icons.forest,
  'grass': Icons.grass,
  'eco': Icons.eco,
  'recycling': Icons.recycling,
  'water_drop': Icons.water_drop,
  'bolt': Icons.bolt,
  'power': Icons.power,
  'electric_bolt': Icons.electric_bolt,
  'lightbulb': Icons.lightbulb,
  'wb_sunny': Icons.wb_sunny,
  'local_fire_department': Icons.local_fire_department,
  'emoji_events': Icons.emoji_events,
  'military_tech': Icons.military_tech,
  'workspace_premium': Icons.workspace_premium,
  'thumb_up': Icons.thumb_up,
};
